FROM python:3.11-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY src/ ./src
COPY artifacts/ ./artifacts

ENV PYTHONUNBUFFERED=1
ENV ARTIFACTS_DIR=/opt/artifacts

ENV PORT=8080
EXPOSE 8080

CMD ["python", "-m", "src.app"]
