services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./backend/artifacts:/artifacts
    environment:
      - ARTIFACTS_DIR=/artifacts
      - PORT=8080
      - ALS_N_CAND=339
      - TOP_K=40

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    env_file:
      - .env
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - RECOMMEND_URL=http://backend:8080/recommend_cached_sasrec
